private
specs

	^{
		{'1.0-beta.8'. #beta. ''. self GLASS10beta8PostDoit. }. "5029 run, 5028 passes, 1 expected failures"
		{'GLASS.230-dkh.231.mcz'. #beta. ''. ''. }. "- 4339 run, 4339 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.230.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.229.mcz'. #beta. ''. ''. }. "- 4336 run, 4336 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.228.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.227.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.226.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.225.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.224.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.223.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.222.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.221.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.220.mcz'. #alpha. self GLASS230dkh220PreDoit. ''. }. "4171 run, 4171 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.219.mcz'. #poison. ''. ''. }. ""
		{'GLASS.230-dkh.218.mcz'. #poison. ''. ''. }. ""
		{'GLASS.230-dkh.217.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.216.mcz'. #beta. ''. ''. }. "4193 run, 4191 passed, 2 failed, 0 errors (failures in non-GLASS packages)"
		{'GLASS.230-dkh.215.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.214.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.213.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.212.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.211.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.210.mcz'. #alpha. ''. ''. }. ""
		{'GLASS.230-dkh.209.mcz'. #beta. ''. ''. }. "4182 run, 4182 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.208.mcz'. #alpha. self GLASS230dkh208PreDoit. ''. }. "4179 run, 4179 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.207.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.206.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.205.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.204.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.203.mcz'. #alpha. ''. ''. }. "4171 run, 4170 passed, 1 failed, 0 errors"
		{'GLASS.230-dkh.202.mcz'. #alpha. ''. ''. }. "4141 run, 4134 passed, 7 failed, 0 errors"
		{'GLASS.230-dkh.201.mcz'. #poison. ''. ''. }. 
		{'GLASS.230-dkh.200.mcz'. #poison. ''. ''. }. "4136 run, 4127 passed, 9 failed, 0 errors"
		{'GLASS.230-dkh.199.mcz'. #poison. ''. ''. }. 
		{'GLASS.230-dkh.198.mcz'. #poison. ''. ''. }. 
		{'GLASS.230-dkh.197.mcz'. #poison. ''. ''. }. 
		{'GLASS.230-dkh.196.mcz'. #poison. ''. ''. }. 
		{'GLASS.230-dkh.195.mcz'. #alpha. ''. ''. }. "4101 run, 4098 passed, 0 failed, 3 errors"
		{'GLASS.230-dkh.194.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.193.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.192.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.191.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.190.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.189.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.188.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.187.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.186.mcz'. #alpha. ''. ''. }. "- 4031 run, 4031 passed, 0 failed, 0 errors"
		{'GLASS.230-dkh.185.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.184.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.183.mcz'. #beta. ''. ''. }. "- 4036 run, 4035 passed, 1 failed, 0 errors (as expected)"
		{'GLASS.230-dkh.182.mcz'. #beta. self GLASS230dkh182PreDoit. ''. }. 
		{'GLASS.230-dkh.181.mcz'. #alpha. ''. ''. }. "- 4034 run, 4033 passed, 1 failed, 0 errors (as expected)"
		{'GLASS.230-dkh.180.mcz'. #alpha. ''. ''. }. "- 4026 run, 4025 passed, 1 failed, 0 errors (as expected)"
		{'GLASS.230-dkh.179.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.178.mcz'. #alpha. ''. ''. }. "- 4021 run, 4020 passed, 1 failed, 0 errors (1 failure in Pier is expected: PRDefinitionDataTest>>testParseBug, see http://code.google.com/p/pier/issues/detail?id=31)"
		{'GLASS.230-dkh.177.mcz'. #release. ''. ''. }. 
		{'GLASS.230-dkh.176.mcz'. #release. ''. ''. }. 
		{'GLASS.230-dkh.175.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.174.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.173.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.172.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.171.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.170.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.169.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.168.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.167.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.166.mcz'. #alpha. ''. ''. }. 
		{'GLASS.230-dkh.165.mcz'. #alpha. ''. ''. }.
		{'GLASS.230-dkh.164.mcz'. #release. ''. ''. }. "xxx"
	}