installation define session section
defineGemToolsSessionOverview
	^HelpTopic 
		title: 'Overview'
		contents:	
'In order to log into the stone using the GemTools Launcher, you must create a session description that includes information such as the hostName for the stone, the name of the stone, GemStone username, password, etc.

There are three different variants of session descriptions that should be used base upon the level of control you need:

  - Appliance Session should be used if you are using a standard GLASS appliance
  - Standard Session should be used if you have native install
  - Custom Session should be used if you need full control of the session description

If you have a GemTools launcher open, you can use the ''New session'' button to create a session description. 

The ''Edit session'' button to change individual field values.'