installation chapter
step7StartStone
	^HelpTopic 
		title: 'Step 8 - Start stone and netldi'
		contents:	
'After installing the GemStone/S server you need to start a stone and a netldi. The netldi process is needed so that the GemTools client can communicate with the stone.

If you are using a native install, then follow the tarting gemstone instructions at http://seaside.gemstone.com/userguide.html#starting-gemstone

If you are using an appliance, you only need to launch the appliance itself, since the stone and netldi processes are started automatically.
'