server chapter
step1GemstoneServerInstall
	^HelpTopic 
		title: 'Step 1 - GemStone/S Server installation'
		contents:	
'If you have experience installing GemStone/S, and are comfortable with setting up Apache or FastCGI and other system and network administration tasks, the native install is a good option:

  - download native install for Linix or Mac from http://seaside.gemstone.com/downloads.html and use the installGemstone.sh script (http://seaside.gemstone.com/scripts/installGemstone.sh)

Alternately:

  - follow the installation instructions at http://seaside.gemstone.com/userguide.html#Linux-installation or http://seaside.gemstone.com/userguide.html#MacOSX-installation
  - follow the getting started instructions at http://seaside.gemstone.com/userguide.html#starting-gemstone

Otherwise, you should consider installing VMWare and then downloading the VMWare GLASS appliance. With the appliance GemStone, the server gems and Apache are automatically started and shutdown, so there''s very little muss and fuss involved:

  - download VMWare GLASS appliance from http://seaside.gemstone.com/downloads.html
  - follow the instructions at http://seaside.gemstone.com/userguide.html#virtual-appliance

Once you have your GemStone server (or appliance) installed, you should follow the instructions for installing GemTools.
'